[package]
name = "iskrac"
version = "0.1.0"
edition = "2024"

[dependencies]
iskrac-lexer = { path = "iskrac-lexer" }
iskrac-interner = { path = "iskrac-interner" }

[workspace]
members = ["iskrac-interner", "iskrac-lexer"]
